<?php

namespace AmuzPackages\DeepLink\Nova\Resources;

use IbrahemKamal\JsonField\JsonField;
use Laravel\Nova\Fields\HasMany;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\URL;
use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Fields\ID;
use App\Nova\Resource;

class DeepLink extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static string $model = \AmuzPackages\DeepLink\Models\DeepLink::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'slug';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id','slug'
    ];

    /**
     * Group of resources - It's autogenerated as module name
     * @var string
     */
    public static $group = "DEEP-LINK";

    public function fields(NovaRequest $request): array
    {
        return [
            ID::make()->sortable(),

            Text::make('슬러그','slug'),

            URL::make('대표 URL','target_url')->nullable()->displayUsing(fn($value)=>$value),

            Text::make('Android Package','aos_package')->nullable(),
            URL::make('Install URL (android)','aos_install_url')->nullable()->displayUsing(fn($value)=>$value),

            Text::make('iOS Bundle Name','ios_bundle')->nullable(),
            URL::make('Install URL (iOS)','ios_install_url')->nullable()->displayUsing(fn($value)=>$value),

            HasMany::make('컨텍스트 링크','linkContexts',LinkContext::class)
        ];
    }

    public function cards(NovaRequest $request): array
    {
        return [];
    }

    public function filters(NovaRequest $request): array
    {
        return [];
    }

    public function lenses(NovaRequest $request): array
    {
        return [];
    }

    public function actions(NovaRequest $request): array
    {
        return [];
    }
}
